### ISSUE TITLE
Connection retry on error?

### ISSUE THREAD

**Issue by jmalonzo** [blesh/RxSocketSubject#6]
Hi Ben,

Is it possible to add support for retying the connection if there's an error? 

Thanks.

**Comment by mr-wildcard** [comment]
Sorry for the late up,

How did you solve this @jmalonzo ?

**Comment by jmalonzo** [comment]
@mr-wildcard I just reconnect on websocket error (i.e. add an onerror handler in RxSocketSubject and reconnect there).

**Comment by BioPhoton** [comment]
Hi @jmalonzo, I'm also trying to deal with errors and reconnection.

Where exactly did you put the errorhandler? in the libs source code?
could you also provide your retry code please?

**Comment by jmalonzo** [comment]
@BioPhoton you can do something like the following.

`let socket = RxSocketSubject.create('ws.example.com', () => console.log('opened'), (error) => {
    // reconnect on error here
});`
